micronaut:
  application:
    name: micronautMongoRabbitmq
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
netty:
  default:
    allocator:
      max-order: 3
db:
  name: store
  collection: products
mongodb:
  uri: mongodb://root:root@localhost:27017/